openapi: 3.0.0
info:
  title: Customer API
  description: Customer API
  version: 1.0.0

paths:
  /customers:
    get:
      summary: Get all customers
      description: 'Get a list of customers with optional filters, pagination, and sorting.'
      tags: [ Customers ]
      operationId: v1ListCustomers
      parameters:
        - name: name
          description: Filter by name
          in: query
          schema:
            type: string
            minLength: 3
            maxLength: 255
        - name: surname
          description: Filter by name
          in: query
          schema:
            type: string
            minLength: 3
            maxLength: 255
        - name: number
          description: Filter by number
          in: query
          schema:
            type: string
            minLength: 3
            maxLength: 255
        - name: active
          description: Filter by active
          in: query
          schema:
            type: boolean
        - name: city
          description: Filter by city
          in: query
          schema:
            type: string
            minLength: 3
            maxLength: 255
        - name: vatNumber
          description: Filter by city
          in: query
          schema:
            type: string
            minLength: 3
            maxLength: 255
        - name: createdBy
          description: Filter by created user
          in: query
          schema:
            type: string
            minLength: 3
            maxLength: 255
        - name: fromCreatedAt
          description: Filter by created date (Greater than or equal)
          in: query
          examples:
            ShortDate:
              value: "2025-01-01"
              summary: Short date string format
            DateTime:
              value: "2025-01-01T00:00:00+01:00"
              summary: Date string format
          schema:
            oneOf:
              - type: string
                format: date
              - type: string
                format: date-time
        - name: toCreatedAt
          description: Filter by created date (Less than or equal)
          in: query
          examples:
            ShortDate:
              value: "2025-01-01"
              summary: Short date string format
            DateTime:
              value: "2025-01-01T00:00:00+01:00"
              summary: Date string format
          schema:
            oneOf:
              - type: string
                format: date
              - type: string
                format: date-time
        - name: page
          description: Set page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          description: Limit rows per page
          in: query
          schema:
            type: integer
            minimum: 5
            maximum: 100
            default: 10
        - name: sort
          description: Sort list by fields
          in: query
          examples:
            SortDesc:
              value: "-createdAt"
              summary: Sort desc
            Multiple:
              value: "-createdAt,+name"
              summary: Multiple
          schema:
            type: string
      responses:
        '200':
          description: 'List of Authors'
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Customer'
                  pagination:
                    $ref: '#/components/schemas/PaginationView'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/JWTNotFound'
        '404':
          $ref: '#/components/responses/ObjectNotFound'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

    post:
      summary: Create a new customer
      description: 'Create a new customer with the provided information.'
      tags: [ Customers ]
      operationId: v1CreateCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerPayload'
      responses:
        '201':
          description: 'Customer created successfully'
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Customer'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/JWTNotFound'
        '404':
          $ref: '#/components/responses/ObjectNotFound'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

  /customers/{customerId}:
    get:
      summary: Get a customer by ID
      description: 'Retrieve a customer by their unique ID.'
      tags: [ Customers ]
      operationId: v1GetCustomerById
      parameters:
        - name: customerId
          description: The unique identifier of the customer
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 'Customer retrieved successfully'
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Customer'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/JWTNotFound'
        '404':
          $ref: '#/components/responses/ObjectNotFound'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

    put:
      summary: Update a customer by ID
      description: 'Update an existing customer with the provided information.'
      tags: [ Customers ]
      operationId: v1UpdateCustomerById
      parameters:
        - name: customerId
          description: The unique identifier of the customer
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerUpdatePayload'
      responses:
        '204':
          description: 'Author updated successfully'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/JWTNotFound'
        '404':
          $ref: '#/components/responses/ObjectNotFound'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

    delete:
      summary: Delete a customer by ID
      description: 'Delete an existing customer by their unique ID.'
      tags: [ Customers ]
      operationId: v1DeleteCustomerById
      parameters:
        - name: customerId
          description: The unique identifier of the customer
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: 'Author deleted successfully'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/JWTNotFound'
        '404':
          $ref: '#/components/responses/ObjectNotFound'
        '500':
          $ref: '#/components/responses/ServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
          format: uuid
        name:
          type: string
          example: John
        surname:
          type: string
          example: Doe
        membership:
          $ref: '#/components/schemas/CustomerMembership'
        contact:
          $ref: '#/components/schemas/ContactInfo'
        address:
          $ref: '#/components/schemas/Address'
        vatNumber:
          type: string
          example: 34567890A
        createdBy:
          type: string
          example: admin
        createdAt:
          type: string
          format: date-time
          example: 2023-06-01T12:00:00Z
        updatedBy:
          type: string
          example: admin
        updatedAt:
          type: string
          format: date-time
          example: 2023-06-01T12:00:00Z

    CustomerMembership:
      type: object
      properties:
        number:
          type: string
          example: SN12345
        active:
          type: boolean
          example: true
        endedAt:
          type: string
          format: date-time
          example: 2024-12-31T23:59:59Z

    CustomerPayload:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: John
        surname:
          type: string
          example: Doe
        contact:
          $ref: '#/components/schemas/ContactInfo'
        address:
          $ref: '#/components/schemas/Address'
        vatNumber:
          type: string
          example: 34567890A

    CustomerUpdatePayload:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: John
        surname:
          type: string
          example: Doe
        membership:
          type: object
          properties:
            active:
              type: boolean
              example: true
        contact:
          $ref: '#/components/schemas/ContactInfo'
        address:
          $ref: '#/components/schemas/Address'
        vatNumber:
          type: string
          example: 34567890A

    ContactInfo:
      type: object
      properties:
        email:
          type: string
          format: email
          example: johndoe@gmail.com
        phone1:
          type: string
          example: +34986543210
        phone2:
          type: string
          example: +34986543210

    Address:
      type: object
      properties:
        street:
          type: string
          example: Main Street
        postalCode:
          type: string
          example: 12345
        city:
          type: string
          example: Anytown
        province:
          type: string
          example: California
        country:
          type: string
          example: USA

    PaginationView:
      type: object
      properties:
        total:
          type: integer
          example: 2
        rowsPerPage:
          type: integer
          example: 10
        page:
          type: integer
          example: 1
        totalPages:
          type: integer
          example: 5

  responses:
    Success:
      description: Success
      content:
        application/json:
          schema:
            properties:
              data:
                type: array
                items:
                  type: string
                example: [ ]

    JWTNotFound:
      description: JWT not Found
      content:
        application/json:
          schema:
            properties:
              message:
                type: string
                example: JWT not Found
              code:
                type: integer
                example: 401

    ObjectNotFound:
      description: Object not Found
      content:
        application/json:
          schema:
            properties:
              message:
                type: string
                example: Object not found
              code:
                type: integer
                example: 404

    BadRequestError:
      description: Bad Request Error
      content:
        application/json:
          schema:
            properties:
              message:
                type: string
                example: Bad Request Error
              code:
                type: integer
                example: 400

    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            properties:
              message:
                type: string
                example: Internal Server Error
              code:
                type: integer
                example: 500

    ServiceUnavailable:
      description: Server Unavailable
      content:
        application/json:
          schema:
            properties:
              message:
                type: string
                example: Server Unavailable
              code:
                type: integer
                example: 503
